Improve tile provider
OPENER-next/OPENER-next pull request #52
Opened 2022-02-03 16:02 UTC by Robbendebiene

2022-02-03 17:10 UTC, 7h30n3 requested changes

2022-02-03 17:10 UTC, 7h30n3 commented on lib/widgets/map_overlay.dart
> +                      onTap: _openCreditsUrl,
I don't see `creditsText` for the used map tiles appended.
(In general)

2022-02-04 08:05 UTC, Robbendebiene commented on lib/commons/tile_layers.dart
> +    creditsText: 'credit text here'
I agree. However currently this text is not shown in the UI. I wanted to implement this in a separate branch.

2022-02-04 08:25 UTC, Robbendebiene commented on lib/widgets/map_overlay.dart
> +  ];
I can see where you are coming from, your approach would lead to a further data structure simplification. At first I've also wanted to generate this map. However this is similar to the maps that we've created in the settings page. It's entirely targeted to the UI where the other stuff is the required underlying data. If we ever want to change the language, your approach won't work any more, or at least not the way it currently does. One could say, that this is already a problem since the credits text is in the TileLayerDefinition, which is true if we want to localize the credits text.
Another reason to separate this is, that in theory we might have more tile layers in the `tileLayers` map than we want to show in the map selector.

The separation was the main reason for me to create an enum, because otherwise I could have just used the keys of the map or the indexes of a list as an identifier in the config.

2022-02-04 08:26 UTC, Robbendebiene commented on lib/widgets/map_overlay.dart
> +                      onTap: _openCreditsUrl,
As mentioned above, this is not part of this PR. I'll plan to create a separate widget that will handle the text and url creation.

2022-02-04 08:32 UTC, Robbendebiene commented on lib/screens/home.dart
> +              final isDarkMode = MediaQuery.of(context).platformBrightness == Brightness.dark;
I've just tested this and it turns out it always uses the system theme. However what we probably want is that it uses our internal theme as long as it is not set to "system". I'll fix that.

2022-02-04 08:43 UTC, 7h30n3 commented on lib/screens/home.dart
> +              final isDarkMode = MediaQuery.of(context).platformBrightness == Brightness.dark;
That was exactly my concern. Thanks.

2022-02-04 12:43 UTC, merged